name: Release
on:
  workflow_call:
    secrets:
      android_keystore:
        required: true
      android_keystore_password:
        required: true
      android_key_alias:
        required: true
      android_key_password:
        required: true
      android_publisher_credentials:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build

      # The built-in plugin @semantic-release/npm requires package.json to exist even if not used
      - name: Create dummy package.json
        run: |
          if [[ -f package.json ]]; then
            echo "Pre-existing package.json file no longer supported" >&2
            exit 1
          fi
          
          echo '{"name": "foo"}' > package.json

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23.0.0
          extra_plugins: |
            @semantic-release/exec@^6.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANDROID_KEYSTORE: ${{ secrets.android_keystore }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
          ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.android_key_alias }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.android_key_password }}
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.android_publisher_credentials }}
