name: Run CI
on:
  workflow_call:
    inputs:
      dokka_docs:
        description: "Whether the project has API documentation powered by Dokka"
        required: false
        type: boolean
        default: true
    secrets:
      maven_username:
        required: true
      maven_password:
        required: true
      maven_central_signing_key_id:
        required: true
      maven_central_signing_key:
        required: true
      maven_central_signing_key_password:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          add-job-summary-as-pr-comment: on-failure

      - name: Generate docs
        if: inputs.dokka_docs
        run: "./gradlew dokkaHtml --scan"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm install
      - name: Publish documentation
        if: inputs.dokka_docs && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          publish_dir: ./build/dokka/html
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.maven_username }}
          MAVEN_PASSWORD: ${{ secrets.maven_password }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.maven_central_signing_key_id }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_central_signing_key }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_central_signing_key_password }}
