name: Run CI
on:
  workflow_call:
    inputs:
      dokka_docs:
        description: "Whether the project has API documentation powered by Dokka"
        required: false
        type: boolean
        default: true
      dokka_docs_path:
        description: "The path to the Dokka documentation"
        required: false
        type: string
        default: "./build/dokka/html"

concurrency:
  group: "release"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm install
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    if: inputs.dokka_docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Generate docs
        uses: eskatos/gradle-command-action@v2
        if: inputs.dokka_docs
        with:
          arguments: dokkaHtml

      - name: Upload artifact
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.dokka_docs_path }}
      - name: Deploy to GitHub Pages
        id: deployment
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions/deploy-pages@v4
