name: Run CI
on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test LTS releases
        java: [11, 17]
    name: "java${{ matrix.java }}-${{ matrix.os }}" # Do not change; used by protected branches
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: eskatos/gradle-command-action@v2
        with:
          arguments: build dokkaHtml
