name: Run CI
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: "17"
        required: false
        description: "The Java versions to test against"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: "java${{ inputs.java_version }}-${{ matrix.os }}" # Do not change; used by protected branches
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: zulu
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          add-job-summary-as-pr-comment: on-failure

      - name: Check
        run: "./gradlew build --scan"
