name: Run CI
on:
  workflow_call:
    inputs:
      dokka_docs:
        description: "Whether the project has API documentation powered by Dokka"
        required: false
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate docs
        uses: eskatos/gradle-command-action@v2
        if: inputs.dokka_docs
        with:
          arguments: dokkaHtml

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm install
      - name: Publish documentation
        if: inputs.dokka_docs && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./build/dokka/html
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
