name: Run CI
on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        node: [16, 18, 20]
    runs-on: ubuntu-latest
    name: "nodejs${{ matrix.node }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: npm ci
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 3
          max_attempts: 3
        timeout-minutes: 10
      - run: npm run static-checks
        timeout-minutes: 3
      - run: npm test
        timeout-minutes: 10
      - run: npm run test:integration
        timeout-minutes: 10
