name: Run CI
on:
  workflow_call:
    inputs:
      nodejs_versions:
        type: string
        default: "[16, 18, 20]"
        required: false
      restrict_integration_tests_to_ubuntu:
        description: "Whether the integration tests should only be run on Ubuntu"
        required: false
        default: false
        type: boolean

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get npm cache directory
        id: npm-cache
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: root-${{ hashFiles('package-lock.json') }}
      - name: npm ci
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 3
          max_attempts: 3
        timeout-minutes: 5
      - run: npm run static-checks

  test:
    needs: static-checks
    strategy:
      matrix:
        node: ${{ fromJson(inputs.nodejs_versions) }}
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "test-nodejs${{ matrix.node }}-${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        uses: nick-fields/retry@v2
        with:
          command: npm ci
          timeout_minutes: 3
          max_attempts: 3
        timeout-minutes: 10
      - run: npm test
        timeout-minutes: 10
      - run: npm run test:integration
        if: "${{ inputs.restrict_integration_tests_to_ubuntu == false || startsWith(matrix.os, 'ubuntu-') }}"
        timeout-minutes: 10
