name: Release
on:
  workflow_call:
    inputs:
      dockerhub_username:
        description: "The Docker Hub username"
        required: true
        type: string
    secrets:
      dockerhub_password:
        description: "The Docker Hub password"
        required: true

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Get npm cache directory
        id: npm-cache
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ hashFiles('**/package-lock.json', '.nvmrc') }}
      - name: Install dependencies
        run: npm ci
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp
      - name: Import Docker image
        run: docker load -i /tmp/docker-image
      - name: Log in to Docker Hub
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
        timeout-minutes: 1
      - name: Log in to GitHub Container Registry
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 1
      - name: Publish Docker image
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/exec@^6.0.3
            @semantic-release/git@^10.0.1
            @semantic-release/changelog@6.0.1
            conventional-changelog-conventionalcommits@4.6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
