name: Run CI
on:
  workflow_call:
    inputs:
      jekyll_docs:
        description: "Whether the project has Jekyll documentation"
        required: false
        type: boolean
        default: false
    secrets:
      npm_token:
        description: "The NPM_TOKEN"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: root-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build

      - uses: actions/setup-ruby@v1
        if: inputs.jekyll_docs
        with:
          ruby-version: '2.5'
      - name: Generate docs
        if: inputs.jekyll_docs
        run: |
          # Jekyll docs:
          gem install bundler
          cd docs
          bundle install --path vendor/bundle
          bundle exec jekyll build

          # TypeDoc docs:
          cd ..
          npm run doc-api

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Publish documentation
        if: steps.release.outputs.new_release_published
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
