name: Run CI
on:
  workflow_call:
    inputs:
      restrict_integration_tests_to_ubuntu:
        description: "Whether the integration tests should only be run on Ubuntu"
        required: false
        default: false
        type: boolean

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: root-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run static-checks

  test:
    needs: static-checks
    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: "test-nodejs${{ matrix.node }}-${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run test:ci:unit
      - run: npm run test:integration
        if: ${{ inputs.restrict_integration_tests_to_ubuntu == false || startsWith(matrix.os, "ubuntu-") }}
