name: Release
on:
  workflow_call:
    inputs:
      jekyll_docs:
        description: "Whether the project has Jekyll documentation"
        required: false
        type: boolean
        default: false
      api_docs:
        description: "Whether the project has API documentation"
        required: false
        type: boolean
        default: false
    secrets:
      npm_token:
        description: "The NPM_TOKEN"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Get npm cache directory
        id: npm-cache
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: root-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build

      - uses: actions/setup-ruby@v1
        if: ${{ inputs.jekyll_docs == true }}
        with:
          ruby-version: '2.5'
      - name: Generate Jekyll docs
        if: ${{ inputs.jekyll_docs == true }}
        run: |
          gem install bundler
          bundle install --path vendor/bundle
          bundle exec jekyll build
        working-directory: docs

      - name: Generate API docs
        if: ${{ inputs.jekyll_docs == true || inputs.api_docs == true }}
        run: npm run doc-api

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Publish documentation
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
