name: Release
on:
  workflow_call:
    inputs:
      main_branch:
        description: "The main branch"
        required: true
        type: string

    secrets:
      ghcr_password:
        description: "GitHub Container Registry password"
        required: true
      helm_repo_access_token:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Install Helm Push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push --version 0.9.0
      - name: Download Docker image
        uses: actions/download-artifact@v2
        with:
          name: docker-image
          path: /tmp
      - name: Import Docker image
        run: docker load -i /tmp/docker-image
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/${{ inputs.main_branch }}'
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: irelaybot
          password: ${{ secrets.ghcr_password }}
      - name: Publish Docker image and Helm chart
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/exec@^5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HELM_REPO_ACCESS_TOKEN: ${{ secrets.helm_repo_access_token }}
