name: CI
on:
  workflow_call:
    inputs:
      docker_image_local_name:
        description: "The local name of the Docker image"
        required: true
        type: string
      nodejs_version:
        description: "The version of Node.js"
        required: false
        default: 16
        type: string
      kubernetes_version:
        description: "The version of Kubernetes"
        required: false
        default: 1.22.15
        type: string
      skaffold_version:
        description: "The version of Skaffold"
        required: false
        default: 1.19.0
        type: string

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.nodejs_version }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ inputs.nodejs_version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - run: npm run static-checks
      - run: npm run test:unit

      - uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      # Check the main chart and the one for backing services
      - run: helm dependency update chart/
      - run: helm dependency update chart/dev-backing-services
      - run: helm lint chart/ --values=chart/values.dev.yml --strict
      - run: helm lint chart/dev-backing-services --values=chart/dev-backing-services/values.yml --strict

      # Functional tests
      - name: Create Kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: default
          kubectl_version: "v${{ inputs.kubernetes_version }}"
          node_image: "kindest/node:v${{ inputs.kubernetes_version }}"
      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@1.4.0
        with:
          command: run
          skaffold-version: ${{ inputs.skaffold_version }}
        env:
          # Work around https://github.com/hiberbee/github-action-skaffold/issues/7
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        timeout-minutes: 10
      - name: Start port-forwarding
        run: .github/scripts/port-forward.sh
      - run: npm run test:functional
        env:
          IS_GITHUB: 'true'
        timeout-minutes: 2
      - name: Output diagnostic information upon failure
        if: failure()
        run: .github/scripts/output-diagnostics.sh

      # Export Docker image so it can be published
      - name: Export Docker image
        run: docker save -o /tmp/docker-image ${{ inputs.docker_image_local_name }}:latest
      - name: Upload Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: /tmp/docker-image
