name: CI for Terraform modules
on:
  workflow_call:
    inputs:
      path:
        description: "The path to the Terraform module"
        required: false
        type: string
        default: ""
      terraform_version:
        description: "The Terraform version"
        required: false
        type: string
        default: "0.14.5"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - run: terraform fmt -check -recursive
        working-directory: ${{ inputs.path }}

      - run: terraform init -backend=false
        working-directory: ${{ inputs.path }}

      - run: terraform validate
        working-directory: ${{ inputs.path }}
