name: CI for Terraform modules
on:
  workflow_call:
    inputs:
      path:
        description: "The path to the Terraform module"
        required: false
        type: string
        default: ""
      terraform_version:
        description: "The Terraform version"
        required: false
        type: string
        default: "1.1.0"
      terraform_validate_dummy_env_vars:
        description: "Dummy variables to pass to terraform validate"
        required: false
        type: string
        default: ""

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - run: terraform fmt -check
        working-directory: ${{ inputs.path }}

      - run: terraform init -backend=false
        working-directory: ${{ inputs.path }}

      - name: Validate Terraform configuration
        working-directory: ${{ inputs.path }}
        run: |
          # Split the comma-separated string into an array
          IFS=',' read -r -a terraform_validate_dummy_env_vars <<< "${{ inputs.terraform_validate_dummy_env_vars }}"
          # Set dummy variables to an empty string
          for var in "${terraform_validate_dummy_env_vars[@]}"; do
            export $var="dummy"
          done
          terraform validate
